<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="MavLinkSharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="ScottPlot.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ViewModels\MainWindowViewModel.*.cs">
      <DependentUpon>MainWindowViewModel.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignalBench.Core\SignalBench.Core.csproj" />
  </ItemGroup>
</Project>
